spring.application.name=url-shortener-sb

server.port=${PORT:8080}

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/url_shortner}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Root@23769}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=thisislongsecretkeybecuaseitisaskingatthebackendsidethatwhyiamputtingthislong
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web.servlet=TRACE

frontend.url=${FRONTEND_URL:http://localhost:5173}